google_analytics: UA-41860599-4

# Enter your Disqus shortname (not your username) to enable commenting on posts
disqus: blog-andrealeopardi

footer-links:
  email: an.leopardi@gmail.com
  github: whatyouhide
  twitter: whatyouhide
  rss: true

# Name of your site (displayed in the header)
title_name: Andrea Leopardi

# Short bio or description (displayed in the header)
title_description: Tech blog

# URL of your avatar or profile pic. Displayed on the top.
avatar_url: https://www.gravatar.com/avatar/faafc04d9e69b73b9f49995fd4c94d4d?s=500

# Your website URL, used for sitemap.xml and your RSS feed.
url: https://andrealeopardi.com

# Appended to {{ site.url }}.
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /posts/:title/

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
